name = "MemoryViews"
uuid = "a791c907-b98b-4e44-8f4d-e4c2362c6b2f"
version = "0.4.0"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]

[deps]
LightBoundsErrors = "e21c612c-4641-4669-b9c3-3f4360ced9da"

[weakdeps]
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
LibDeflate = "9255714d-24a7-4b30-8ea3-d46a97f7e13b"

[extensions]
StringViewsExt = "StringViews"
FixedSizeArraysExt = "FixedSizeArrays"
LibDeflateExt = "LibDeflate"

[compat]
Aqua = "0.8.7"
StringViews = "1"
FixedSizeArrays = "1"
LibDeflate = "0.4"
LightBoundsErrors = "1.1"
Test = "1.11"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "FixedSizeArrays", "StringViews", "Test", "LibDeflate"]
