name = "MemViews"
uuid = "a791c907-b98b-4e44-8f4d-e4c2362c6b2f"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]
version = "0.1.0"

[compat]
Test = "1.11"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
